Issue resolved #128 #129 #130 #131
Udyam/ees23-frontend pull request #153
Opened 2023-03-18 07:23 UTC by mdathar4403

2023-03-20 07:27 UTC, Ankur-Agrawal-ece20 requested changes

2023-03-20 07:27 UTC, Ankur-Agrawal-ece20 commented on src/index.js
> +const clientId = 'test';
Change this back to the previous line.

2023-03-24 17:23 UTC, mdathar4403 commented
ees Navbar corrected

2023-03-26 11:42 UTC, Ankur-Agrawal-ece20 requested changes

2023-03-26 11:42 UTC, Ankur-Agrawal-ece20 commented on src/index.js
> +const clientId = 'test';
const clientId = process.env.REACT_APP_CLIENT_ID;
this should be the code

2023-03-28 08:42 UTC, RainaJain5 requested changes
Add a light color background behind navbar and increase space between all elements of navbar. 
Rename images in mashal events as per the file name added.

2023-03-30 13:35 UTC, Ankur-Agrawal-ece20 approved these changes

2023-03-30 13:35 UTC, merged